# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import controlPanel_pb2 as controlPanel__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controlPanel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPanelServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ManageGPUServer = channel.unary_unary(
                '/ControlPanelService/ManageGPUServer',
                request_serializer=controlPanel__pb2.GPUServerRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.GPUServerResponse.FromString,
                _registered_method=True)
        self.UpdateThrottlingConfig = channel.unary_unary(
                '/ControlPanelService/UpdateThrottlingConfig',
                request_serializer=controlPanel__pb2.ThrottlingRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.ThrottlingResponse.FromString,
                _registered_method=True)
        self.UpdatePem = channel.unary_unary(
                '/ControlPanelService/UpdatePem',
                request_serializer=controlPanel__pb2.UpdatePemRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.UpdatePemResponse.FromString,
                _registered_method=True)
        self.UpdateModelList = channel.unary_unary(
                '/ControlPanelService/UpdateModelList',
                request_serializer=controlPanel__pb2.UpdateModelListRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.UpdateModelListResponse.FromString,
                _registered_method=True)
        self.UpdateSharedSecret = channel.unary_unary(
                '/ControlPanelService/UpdateSharedSecret',
                request_serializer=controlPanel__pb2.UpdateSharedSecretRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.UpdateSharedSecretResponse.FromString,
                _registered_method=True)
        self.UpdatePrivateKey = channel.unary_unary(
                '/ControlPanelService/UpdatePrivateKey',
                request_serializer=controlPanel__pb2.UpdatePrivateKeyRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.UpdatePrivateKeyResponse.FromString,
                _registered_method=True)
        self.UpdateComputeUnit = channel.unary_unary(
                '/ControlPanelService/UpdateComputeUnit',
                request_serializer=controlPanel__pb2.UpdateComputeUnitRequest.SerializeToString,
                response_deserializer=controlPanel__pb2.UpdateComputeUnitResponse.FromString,
                _registered_method=True)


class ControlPanelServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ManageGPUServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateThrottlingConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSharedSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrivateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComputeUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPanelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ManageGPUServer': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageGPUServer,
                    request_deserializer=controlPanel__pb2.GPUServerRequest.FromString,
                    response_serializer=controlPanel__pb2.GPUServerResponse.SerializeToString,
            ),
            'UpdateThrottlingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateThrottlingConfig,
                    request_deserializer=controlPanel__pb2.ThrottlingRequest.FromString,
                    response_serializer=controlPanel__pb2.ThrottlingResponse.SerializeToString,
            ),
            'UpdatePem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePem,
                    request_deserializer=controlPanel__pb2.UpdatePemRequest.FromString,
                    response_serializer=controlPanel__pb2.UpdatePemResponse.SerializeToString,
            ),
            'UpdateModelList': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelList,
                    request_deserializer=controlPanel__pb2.UpdateModelListRequest.FromString,
                    response_serializer=controlPanel__pb2.UpdateModelListResponse.SerializeToString,
            ),
            'UpdateSharedSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSharedSecret,
                    request_deserializer=controlPanel__pb2.UpdateSharedSecretRequest.FromString,
                    response_serializer=controlPanel__pb2.UpdateSharedSecretResponse.SerializeToString,
            ),
            'UpdatePrivateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrivateKey,
                    request_deserializer=controlPanel__pb2.UpdatePrivateKeyRequest.FromString,
                    response_serializer=controlPanel__pb2.UpdatePrivateKeyResponse.SerializeToString,
            ),
            'UpdateComputeUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComputeUnit,
                    request_deserializer=controlPanel__pb2.UpdateComputeUnitRequest.FromString,
                    response_serializer=controlPanel__pb2.UpdateComputeUnitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ControlPanelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ControlPanelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPanelService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ManageGPUServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/ManageGPUServer',
            controlPanel__pb2.GPUServerRequest.SerializeToString,
            controlPanel__pb2.GPUServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateThrottlingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdateThrottlingConfig',
            controlPanel__pb2.ThrottlingRequest.SerializeToString,
            controlPanel__pb2.ThrottlingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdatePem',
            controlPanel__pb2.UpdatePemRequest.SerializeToString,
            controlPanel__pb2.UpdatePemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdateModelList',
            controlPanel__pb2.UpdateModelListRequest.SerializeToString,
            controlPanel__pb2.UpdateModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSharedSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdateSharedSecret',
            controlPanel__pb2.UpdateSharedSecretRequest.SerializeToString,
            controlPanel__pb2.UpdateSharedSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrivateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdatePrivateKey',
            controlPanel__pb2.UpdatePrivateKeyRequest.SerializeToString,
            controlPanel__pb2.UpdatePrivateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComputeUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControlPanelService/UpdateComputeUnit',
            controlPanel__pb2.UpdateComputeUnitRequest.SerializeToString,
            controlPanel__pb2.UpdateComputeUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
