# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import imageService_pb2 as imageService__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in imageService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageGenerationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateImage = channel.unary_stream(
                '/ImageGenerationService/GenerateImage',
                request_serializer=imageService__pb2.ImageGenerationRequest.SerializeToString,
                response_deserializer=imageService__pb2.ImageGenerationResponse.FromString,
                _registered_method=True)
        self.FilesExist = channel.unary_unary(
                '/ImageGenerationService/FilesExist',
                request_serializer=imageService__pb2.FileListRequest.SerializeToString,
                response_deserializer=imageService__pb2.FileExistenceResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_stream(
                '/ImageGenerationService/UploadFile',
                request_serializer=imageService__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=imageService__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Echo = channel.unary_unary(
                '/ImageGenerationService/Echo',
                request_serializer=imageService__pb2.EchoRequest.SerializeToString,
                response_deserializer=imageService__pb2.EchoReply.FromString,
                _registered_method=True)
        self.Pubkey = channel.unary_unary(
                '/ImageGenerationService/Pubkey',
                request_serializer=imageService__pb2.PubkeyRequest.SerializeToString,
                response_deserializer=imageService__pb2.PubkeyResponse.FromString,
                _registered_method=True)
        self.Hours = channel.unary_unary(
                '/ImageGenerationService/Hours',
                request_serializer=imageService__pb2.HoursRequest.SerializeToString,
                response_deserializer=imageService__pb2.HoursResponse.FromString,
                _registered_method=True)


class ImageGenerationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilesExist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pubkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateImage': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=imageService__pb2.ImageGenerationRequest.FromString,
                    response_serializer=imageService__pb2.ImageGenerationResponse.SerializeToString,
            ),
            'FilesExist': grpc.unary_unary_rpc_method_handler(
                    servicer.FilesExist,
                    request_deserializer=imageService__pb2.FileListRequest.FromString,
                    response_serializer=imageService__pb2.FileExistenceResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_stream_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=imageService__pb2.FileUploadRequest.FromString,
                    response_serializer=imageService__pb2.UploadResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=imageService__pb2.EchoRequest.FromString,
                    response_serializer=imageService__pb2.EchoReply.SerializeToString,
            ),
            'Pubkey': grpc.unary_unary_rpc_method_handler(
                    servicer.Pubkey,
                    request_deserializer=imageService__pb2.PubkeyRequest.FromString,
                    response_serializer=imageService__pb2.PubkeyResponse.SerializeToString,
            ),
            'Hours': grpc.unary_unary_rpc_method_handler(
                    servicer.Hours,
                    request_deserializer=imageService__pb2.HoursRequest.FromString,
                    response_serializer=imageService__pb2.HoursResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageGenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageGenerationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ImageGenerationService/GenerateImage',
            imageService__pb2.ImageGenerationRequest.SerializeToString,
            imageService__pb2.ImageGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilesExist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageGenerationService/FilesExist',
            imageService__pb2.FileListRequest.SerializeToString,
            imageService__pb2.FileExistenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ImageGenerationService/UploadFile',
            imageService__pb2.FileUploadRequest.SerializeToString,
            imageService__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageGenerationService/Echo',
            imageService__pb2.EchoRequest.SerializeToString,
            imageService__pb2.EchoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pubkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageGenerationService/Pubkey',
            imageService__pb2.PubkeyRequest.SerializeToString,
            imageService__pb2.PubkeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageGenerationService/Hours',
            imageService__pb2.HoursRequest.SerializeToString,
            imageService__pb2.HoursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
