# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoRA(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoRA()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoRA(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoRA
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoRA
    def File(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoRA
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.6

    # LoRA
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def LoRAStart(builder):
    builder.StartObject(3)

def Start(builder):
    LoRAStart(builder)

def LoRAAddFile(builder, file):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(file), 0)

def AddFile(builder, file):
    LoRAAddFile(builder, file)

def LoRAAddWeight(builder, weight):
    builder.PrependFloat32Slot(1, weight, 0.6)

def AddWeight(builder, weight):
    LoRAAddWeight(builder, weight)

def LoRAAddMode(builder, mode):
    builder.PrependInt8Slot(2, mode, 0)

def AddMode(builder, mode):
    LoRAAddMode(builder, mode)

def LoRAEnd(builder):
    return builder.EndObject()

def End(builder):
    return LoRAEnd(builder)
